# Generated by Django 3.2.8 on 2021-10-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20211009_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoallproxy',
            options={'verbose_name': 'All Video', 'verbose_name_plural': 'All Videos'},
        ),
    ]
