# Generated by Django 3.2.8 on 2021-10-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20211012_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videos_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
