# Generated by Django 3.2.8 on 2021-10-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20211014_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
